PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, fb_id TEXT, acct_type INTEGER, acct_status INTEGER, login_stat INTEGER, email TEXT, fname TEXT, lname TEXT, date_created TEXT, date_approved TEXT);
CREATE TABLE account_status (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, acct_stat_name TEXT);
CREATE TABLE account_login (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, login_stat TEXT);
CREATE TABLE account_type (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, acct_type TEXT);
CREATE TABLE farmer_info (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, _01fname TEXT, _02midname TEXT, _03lname TEXT, _04mobileno TEXT, _05homeadd TEXT, _06area TEXT, _07numplots TEXT, _dcreate TEXT, _did TEXT, _dsynced TEXT, _dtmod TEXT, _fid TEXT, _isSynced TEXT, _plotno TEXT, _status TEXT, _userid TEXT, _year TEXT);
CREATE TABLE farmland_setup (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, _06loc TEXT, _07pdate TEXT, _08hvdate TEXT, _09soil TEXT, _10eco TEXT, _dcreate TEXT, _did TEXT, _dsynced TEXT, _dtmod TEXT, _fid TEXT, _isSynced TEXT, _plotno TEXT, _status TEXT, _userid TEXT, _year TEXT);
CREATE TABLE soil_type (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, soil TEXT);
CREATE TABLE economic_zone (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, ecozone TEXT);
CREATE TABLE fertilizer_application (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, fapp TEXT);
CREATE TABLE fertilizer_app_new (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, fnew TEXT);
CREATE TABLE fertilizer_basal (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, _01map TEXT, _02rate TEXT, _03type TEXT, _04qty TEXT, _dcreate TEXT, _did TEXT, _dsynced TEXT, _dtmod TEXT, _fid TEXT, _isSynced TEXT, _plotno TEXT, _status TEXT, _userid TEXT, _year TEXT);
CREATE TABLE fertilizer_top (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, _01map TEXT, _02rate TEXT, _03type TEXT, _04qty TEXT, _dcreate TEXT, _did TEXT, _dsynced TEXT, _dtmod TEXT, _fid TEXT, _isSynced TEXT, _plotno TEXT, _status TEXT, _userid TEXT, _year TEXT);
CREATE TABLE fertilizer_side (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, _01map TEXT, _02rate TEXT, _03type TEXT, _04qty TEXT, _dcreate TEXT, _did TEXT, _dsynced TEXT, _dtmod TEXT, _fid TEXT, _isSynced TEXT, _plotno TEXT, _status TEXT, _userid TEXT, _year TEXT);
CREATE TABLE photos (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, _dcreate TEXT, _did TEXT, _dsynced TEXT, _dtmod TEXT, _fid TEXT, _isSynced TEXT, _plotno TEXT, _status TEXT, _url_local TEXT, _url_online TEXT, _userid TEXT, _year TEXT);
CREATE TABLE cultural_mngt (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, _01dlandprep TEXT, _02noplow TEXT, _03noharrow TEXT, _04soil TEXT, _05terrain TEXT, _06dcropest TEXT, _07cropestmethod TEXT, _08varietyplanted TEXT, _09pdist_prow TEXT, _11pesticiderate TEXT, _12freq TEXT, _13dose TEXT, _14pstcide_type TEXT, _15srctype TEXT, _16srcname TEXT, _dcreate TEXT, _did TEXT, _dsynced TEXT, _dtmod TEXT, _fid TEXT, _isSynced TEXT, _plotno TEXT, _status TEXT, _userid TEXT, _year TEXT);
CREATE TABLE pest_disease (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, _01muni TEXT, _02brgy TEXT, _03whiteflies TEXT, _04mites TEXT, _05mealybugs TEXT, _06witchb_symptoms TEXT, _07cblight TEXT, _08cmosaic TEXT, _09anthracnose TEXT, _10rot TEXT, _11growthstg TEXT, _12areapl TEXT, _13areainfect TEXT, _14varietyinfect TEXT, _15deg TEXT, _dcreate TEXT, _did TEXT, _dsynced TEXT, _dtmod TEXT, _fid TEXT, _isSynced TEXT, _plotno TEXT, _status TEXT, _userid TEXT, _year TEXT);
CREATE TABLE production (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, _01hvdate TEXT, _02hvmethod TEXT, _03yieldhect TEXT, _04rootspl TEXT, _dcreate TEXT, _did TEXT, _dsynced TEXT, _dtmod TEXT, _fid TEXT, _isSynced TEXT, _plotno TEXT, _status TEXT, _userid TEXT, _year TEXT);
CREATE TABLE notes (id INTEGER PRIMARY KEY AUTOINCREMENT, _id INTEGER, _01note TEXT, _dcreate TEXT, _did TEXT, _dsynced TEXT, _dtmod TEXT, _fid TEXT, _isSynced TEXT, _plotno TEXT, _status TEXT, _userid TEXT, _year TEXT);
COMMIT;